export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG'


export const THONG_TIN_NGUOI_DUNG_DAT_VE = 'THONG_TIN_NGUOI_DUNG_DAT_VE'

export const SET_DANH_SACH_NGUOI_DUNG = "SET_DANH_SACH_NGUOI_DUNG"

export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = 'LAY_DANH_SACH_LOAI_NGUOI_DUNG'